monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 225  # distance of participant from monitor (in cm)
  gamma: 2.1  # specific value for gamma correction
  verbose: True

window:
  units: pix
  screen: 1

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  aperture_radius: 1500
  fix_radius: 2.5
  fix_color: 0.5
  fix_line_width: 0.7
  stim_size_pixels: 1080
  frequency: 15
  bg_stim_h5file: 'stims_512.h5'
  bg_stim_url: 'https://figshare.com/ndownloader/files/36259086'

design:
  n_trials: 32
  mean_iti_duration: 6.0
  minimal_iti_duration: 3.0
  maximal_iti_duration: 18.0
  total_iti_duration_leeway: 2.0
  start_duration: 20
  end_duration: 20
  stim_duration: 3
  target_window_length: 5 # <<<<<<<<<<<<<<<< THIS VARIABLE LUISA!!! each image is on the screen for (1/frequency), so 0.2s if frequency=15
  isi_file: "itis_shuffled.txt"

various:
  piechart_width: 1
  text_width: 250
  text_height: 25
  buttons: ['b', 'e', 'j', 'k', 'l', 'semicolon']
  button_size: 2
