window:
    size: [1920, 1080]
    # size: [2304,1440]
    screen: 1
    pos: [0,0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True
    allowStencil: True

monitor:
    name: default
    width: 69.8  # in cm
    distance: 196  # in cm
    gamma: 2.1

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  Size_fixation_dot_in_degrees: 0.035  # in deg
  aperture_radius: 1500
  fix_radius: 2.5
  fix_color: 0.5
  fix_line_width: 0.7
  angular_cycles: 8
  radial_cycles: 8
  border_radius: 0.2
  n_mask_pixels: 1000
  frequency: 8
  pacman_angle: 5
  contrasts: [0.75,1]
  # stim_sizes: [0.13, 0.67, 1.28, 2.01, 2.68, 3.35, 4.02]
  stim_sizes: [0.77, 1.28, 1.59, 1.93, 3]
  cue_size: 0.15
  cue_color: [-1,1,-1]
  prf_color: "#000000"

design:
  stim_repetitions: 5 # 25 stims in 6 mins
  mean_iti_duration: 7.0
  minimal_iti_duration: 5.0
  maximal_iti_duration: 18.0
  total_iti_duration_leeway: 2.0
  start_duration: 24
  end_duration: 24
  stim_duration: 1.5
  cue_time: 0.5
  static_isi: 2
  custom_isi: True

various:
  piechart_width: 1
  text_width: 150
  text_height: 0.5
  buttons: ['b', 'e', 'j', 'k', 'l', 'semicolon']
  button_size: 2
  fixation_width: 2
  fixation_color: 'black'

Task_settings: 
  response_interval: 0.8 # time in s you allow the participant to respond that still counts as correct response
  color_switch_interval: 3.5 # interval in s between color dot switches, note: a random decimal between -1 and +1 is added to it in the code 
