monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 225  # distance of participant from monitor (in cm)
  gamma: 1  # specific value for gamma correction
  verbose: True

window:
  units: pix

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  aperture_radius: 1500
  fix_radius: 2.5
  fix_color: 0.5
  fix_line_width: 0.7
  angular_cycles: 4
  radial_cycles: 1
  border_radius: 0.2
  n_mask_pixels: 1000
  frequency: 8
  pacman_angle: 5
  contrasts: [0.6,1]
  # stim_sizes: [0.13, 0.67, 1.28, 2.01, 2.68, 3.35, 4.02]
  stim_sizes: [0.77, 1.28, 1.59, 1.93, 3]
  cue_size: 0.15
  cue_color: [-1,1,-1]
  prf_color: "#000000"

design:
  stim_repetitions: 12 # ~571s | = 30 iter = ~1171.97s (incl 24s)
  intended_duration: 1200
  mean_iti_duration: 6.0
  minimal_iti_duration: 3.0
  maximal_iti_duration: 18.0
  total_iti_duration_leeway: 2.0
  start_duration: 24
  end_duration: 24
  stim_duration: 1.5
  cue_time: 0.5

various:
  piechart_width: 1
  text_width: 250
  text_height: 25
  buttons: ['b', 'e', 'j', 'k', 'l', 'semicolon']
  button_size: 2
