monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 225  # distance of participant from monitor (in cm)
  gamma: 1  # specific value for gamma correction
  verbose: True

window:
  units: pix

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  aperture_radius: 1500
  fix_radius: 2.5
  fix_color: 0.5
  angular_cycles: 25
  radial_cycles: 0
  border_radius: 0.5
  n_mask_pixels: 0
  frequency: 8
  pacman_angle: 5

design:
  n_trials: 120
  mean_iti_duration: 6.0
  minimal_iti_duration: 3.0
  maximal_iti_duration: 18.0
  total_iti_duration_leeway: 2.0
  start_duration: 0
  end_duration: 24
  stim_duration: 0.75

various:
  piechart_width: 1 
  text_width: 250
  text_height: 25
  buttons: ['b', 'j', 'k', 'l', 'semicolon']
  button_size: 2  