window:
    size: [1920, 1080]
    screen: 1
    pos: [0, 0]
    color: [0, 0, 0]
    fullscr: True
    winType: pyglet
    waitBlanking: True

monitor:
    name: default
    width: 69.8  # in cm
    distance: 196  # in cm
    gamma: 2.1

eyetracker:
  address: '100.1.1.1'
  options:
    calibration_type: HV5

stimuli:
  dot_size: 4  # in deg
  aperture_radius: 1500
  angular_cycles: 10
  radial_cycles: 12
  border_radius: 0.2
  n_mask_pixels: 1000
  frequency: 8
  stim_sizes: [1,3]

design:
  n_trials: 62 # ~542.52s (similar to lineprf2 exp; 13 linescanning dynamics)
  intended_duration: 1200
  mean_iti_duration: 6.0
  minimal_iti_duration: 3.0
  maximal_iti_duration: 18.0
  total_iti_duration_leeway: 2.0
  start_duration: 24
  end_duration: 24
  stim_duration: 2

various:
  piechart_width: 1
  text_width: 150
  text_height: 0.5
  buttons: ['b', 'e', 'j', 'k', 'l', 'semicolon']
  button_size: 2

Task_settings: 
  response_interval: 0.8 # time in s you allow the participant to respond that still counts as correct response
  color_switch_interval: 3.5 # interval in s between color dot switches, note: a random decimal between -1 and +1 is added to it in the code 