monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 225  # distance of participant from monitor (in cm)
  gamma: 1  # specific value for gamma correction
  verbose: True

window:
  units: pix
  screen: 1

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  aperture_radius: 1500
  fix_radius: 2.5
  fix_color: 0.5
  fix_line_width: 0.7
  angular_cycles: 4
  radial_cycles: 1
  border_radius: 0.2
  n_mask_pixels: 1000
  stim_width: 1000
  stim_height: 100

design:
  n_trials: 28 # ~571s | = 30 iter = ~1171.97s (incl 24s)
  mean_iti_duration: 6.0
  minimal_iti_duration: 3.0
  maximal_iti_duration: 18.0
  total_iti_duration_leeway: 2.0
  start_duration: 20
  end_duration: 20
  stim_duration: 3
  cue_time: 0.5
  unilateral_hand: "left"

various:
  piechart_width: 1
  text_width: 250
  text_height: 25
  buttons: ['b', 'e', 'j', 'k', 'l', 'semicolon']
  button_size: 2
  fixation_width: 15
  fixation_color: 'black'
