monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 225  # distance of participant from monitor (in cm)
  gamma: 1  # specific value for gamma correction
  verbose: True

window:
  units: pix
  screen: 1

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  aperture_radius: 1500
  fix_radius: 2.5
  fix_color: 0.5
  fix_line_width: 0.7
  angular_cycles: 10
  radial_cycles: 12
  border_radius: 0.2
  n_mask_pixels: 1000
  frequency: 8
  pacman_angle: 5
  cue_size: 0.15
  cue_color: [-1,1,-1]
  prf_color: "#000000"

design:
  sync: True
  t_r: 0.008333
  nsa: 10
  dyns: 250
  fixed_iti: False
  mean_iti_duration: 0.3
  minimal_iti_duration: 0.25
  maximal_iti_duration: 0.35
  total_iti_duration_leeway: 0.2
  start_duration: 0
  end_duration: 0
  stim_duration: 0.016

various:
  piechart_width: 1
  text_width: 250
  text_height: 25
  buttons: ['b', 'e', 'j', 'k', 'l', 'semicolon']
  button_size: 2
