monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 225  # distance of participant from monitor (in cm)
  gamma: 1  # specific value for gamma correction
  verbose: True

window:
  units: pix
  screen: 1

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  aperture_radius: 1500
  fix_radius: 0.04
  fraction_aperture_size: 0.7
  fix_color: 0.5
  angular_cycles: 8
  radial_cycles: 8
  border_radius: 0.2
  n_mask_pixels: 0
  frequency: 8
  bar_width_deg: 0.625
  squares_in_bar: 1
  thick bar as scalar of thin bar: 2
  pacman_angle: 5
  Size fixation dot in degrees: 2
  cue_size: 0.15
  cue_color: "#000000"

design:
  # n_trials: 5
  use_static_isi: True
  fix_change_prob: 0.05
  intended_duration: 0 #1200 # for 20 min run # for 3.5 min run: 210
  static_isi: 0
  mean_iti_duration: 6.0
  minimal_iti_duration: 3.0
  maximal_iti_duration: 18.0
  total_iti_duration_leeway: 2.0
  stim_duration: 0.250 #0.63
  aperture_factor_of_prf_size: 6
  start_duration: 20 #30 # = 1.5 sweeps
  blank_duration: 15
  end_duration: 20
  span_locations: [-7,7]
  bar_steps: 60
  inter_sweep_blank: 15
  stim_repetitions: 2 # 1 iter = 1040 trials = 260 (s). + 20s outro = 280s = 13 dynamics of ME

various:
  piechart_width: 1
  text_width: 250
  text_height: 25
  buttons: ['b', 'e', 'j', 'k', 'l', 'semicolon']
  button_size: 2

Task settings: 
  response interval: 0.8 # time in s you allow the participant to respond that still counts as correct response
  color switch interval: 3.5 # interval in s between color dot switches, note: a random decimal between -1 and +1 is added to it in the code 