monitor:
  name: 7T
  width: 69  # width of monitor (in cm)
  distance: 225  # distance of participant from monitor (in cm)
  gamma: 1  # specific value for gamma correction
  verbose: True

window:
  units: pix

eyetracker:
  address: '100.1.1.1'
  dot_size: 0.1  # in deg
  options:
    calibration_type: HV5

stimuli:
  aperture_radius: 1500
  fix_radius: 0.04
  fraction_aperture_size: 0.7
  fix_color: 0.5
  angular_cycles: 8
  radial_cycles: 8
  border_radius: 0.2
  n_mask_pixels: 0
  frequency: 8
  bar_width_deg: 0.625
  squares_in_bar: 1
  pacman_angle: 5
  Size fixation dot in degrees: 2
  cue_size: 0.15
  cue_color: "#000000"

design:
  # n_trials: 5
  use_static_isi: True
  fix_change_prob: 0.05
  intended_duration: 0 #1200 # for 20 min run # for 3.5 min run: 210
  stim_repetitions: 3 # 1 iter = 640 trials = 160s (+30s start = 190) # 7 iter = 4480 trials = 1120s (30s start = 1150 = 19.1 minutes)
  static_isi: 0
  mean_iti_duration: 6.0
  minimal_iti_duration: 3.0
  maximal_iti_duration: 18.0
  total_iti_duration_leeway: 2.0
  start_duration: 30 # = 1.5 sweeps
  end_duration: 0
  stim_duration: 0.250 #0.63
  aperture_factor_of_prf_size: 6
  horizontal_locations: [-3.   , -2.846, -2.692, -2.538, -2.385, -2.231, -2.077, -1.923,
       -1.769, -1.615, -1.462, -1.308, -1.154, -1.   , -0.846, -0.692,
       -0.538, -0.385, -0.231, -0.077,  0.077,  0.231,  0.385,  0.538,
        0.692,  0.846,  1.   ,  1.154,  1.308,  1.462,  1.615,  1.769,
        1.923,  2.077,  2.231,  2.385,  2.538,  2.692,  2.846,  3.   ]
  vertical_locations: [-3.   , -2.846, -2.692, -2.538, -2.385, -2.231, -2.077, -1.923,
       -1.769, -1.615, -1.462, -1.308, -1.154, -1.   , -0.846, -0.692,
       -0.538, -0.385, -0.231, -0.077,  0.077,  0.231,  0.385,  0.538,
        0.692,  0.846,  1.   ,  1.154,  1.308,  1.462,  1.615,  1.769,
        1.923,  2.077,  2.231,  2.385,  2.538,  2.692,  2.846,  3.   ]

  # horizontal_locations: [-3,0,3]
  # vertical_locations: [-3,0,3]

various:
  piechart_width: 1
  text_width: 250
  text_height: 25
  buttons: ['b', 'e', 'j', 'k', 'l', 'semicolon']
  button_size: 2

Task settings: 
    response interval: 0.8 # time in s you allow the participant to respond that still counts as correct response
    color switch interval: 3.5 # interval in s between color dot switches, note: a random decimal between -1 and +1 is added to it in the code 